services:
  postgres:
    image: postgres:15
    container_name: ShoonitDB
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-ShoonitDB2024}
      - POSTGRES_DB=${DB_NAME:-ShoonitDB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network      

  api:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    container_name: Shoonit-API
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=ShoonitDB2024
      - DB_HOST=postgres    # This should match the service name
      - DB_PORT=5432
      - DB_NAME=ShoonitDB      
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network        
    volumes:
      - ../:/app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
